### ISSUE TITLE
在NLU中bert 的输入没有AB句子的向量吗？

### ISSUE THREAD

**Issue by LLLLLLoki** [thu-coai/CrossWOZ#11]
在NLU 过程中 ，输入只有id_embedding, mask_embedding, 没有看到segment_embedding,

**Comment by zqwerty** [comment]
输入是单句，不需要区分segment

**Comment by LLLLLLoki** [comment]
我说的是上下文的context 这个输入  ，不是三句话吗，['CLS'] + sen1 + ['SEP'] + sen2 +['SEP'] + sen3 + ['SEP'] ,这里好像没有segment，当初是因为3句话没有加入segment 还是把他们当作一句话呢？

**Comment by zqwerty** [comment]
当做一句话
