### ISSUE TITLE
是否可以开源数据标注部分的代码

### ISSUE THREAD

**Issue by anbo724** [thu-coai/CrossWOZ#12]
感谢分享非常赞的论文和数据集，论文中提到“We developed a specialized website that allows two workers to converse synchronously and make annotations online.”。
我们也希望标注一些领域数据，并且准备开放给科研社区使用，但是从头开发相关的标注系统有些繁琐。
是否可以将数据标注部分的代码开源或者分享，谢谢 anbo@iscas.ac。

**Comment by zqwerty** [comment]
我们考虑将数据收集网站的代码写的更通用、可配置性更强之后开源
