### ISSUE TITLE
如何通过标注好的数据来获取句子中每个词(字)的标签 ？

### ISSUE THREAD

**Issue by xhr-catcher** [thu-coai/CrossWOZ#13]
您好，请问该如何通过标注好的数据来获取句子中每个词(字)的标签呢？
如用户输入："你好，我想吃美食街，帮我推荐一个人均消费在50-100元的餐馆，谢谢。"
数据集中标注的信息是：
[
['General', 'greet', 'none', 'none'], 
['General', 'thank', 'none', 'none'], 
['Inform', '餐馆', '人均消费', '50-100元'],
['Inform', '餐馆', '推荐菜', '美食街'],
['Request', '餐馆', '名称', '']
]
需要对“美食街”标注上"B-Inform_餐馆_推荐菜"，对"50-100元"标注上"B-Inform_餐馆_人均消费"，其余的词(字)标注为O
直接使用字符串匹配吗？但那样可能会出现词(字)相同标签却不同的问题。
不知道是否在标注数据的时候同时记录了该词(字)在句中的位置呢？

**Comment by zqwerty** [comment]
没有在标注时记录，目前是通过字符串匹配的方法找出来的：https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/nlu/jointBERT/crosswoz/preprocess.py#L51

**Comment by xhr-catcher** [comment]
嗯嗯，好的，谢谢！
