### ISSUE TITLE
policy module 如何執行 evalue.py?

### ISSUE THREAD

**Issue by alznn** [thu-coai/CrossWOZ#15]
您好，如標題
我將 NLU DST 個別 train 好以後，做到 policy module 時，按照 readme 文件，先執行 python train.py，最後一次 epoch 顯示 loss_a 在0.035，train 完後畫面如下：
![圖片](https://user-images.githubusercontent.com/11405478/91156012-309a8e00-e6f6-11ea-967c-f16481049c5f.png)

接下來執行 python evalue.py 時，發現 predict_da 均回傳空 list，導致分數很低，

當我回去 trace code 到 class MLEAbstract 時，發現  action = self.vector.action_devectorize(a.numpy()) 本身就是回傳空 list 回來，而上一行中的 a = self.policy.select_action(s_vec.to(device=DEVICE), False).cpu()，再往上 trace 的 policy.policy  的檔案中，policy 基本上沒又東西，回去看 util 的 module 同樣都是 init ，沒辦法回去 trace policy 來自於哪個 object，因此無法檢查 select_action 是否有作用，

想請教這段過程中，我遺漏了哪些步驟，或是哪邊流程錯誤，才可以在 policy evalue.py 的部分成功預測?

謝謝您

**Comment by zqwerty** [comment]
抱歉回复的晚了。我估计你是安装了convlab-2的环境，那个里面mle policy code有改动，所以如果用那个环境跑这个代码，会导致你这个问题。你可以重新安装这个repo的环境，是能够复现paper的结果的。

**Comment by alznn** [comment]
當時發生這個 issue 時，就是使用此 repo ，後來循線摸索到 convlab，另外開一個新的環境裝 convlab-2 ，並全部切到 convlab-2 使用，在 convlab-2 中，policy mle 部分，evalue.py 不斷出現下圖錯誤
![圖片](https://user-images.githubusercontent.com/11405478/95352394-c9771880-08f4-11eb-8f60-2322a0b5d64a.png)

目前算是先跳過這個 issue 不管了

**Comment by zqwerty** [comment]
> 抱歉回复的晚了。我估计你是安装了convlab-2的环境，那个里面mle policy code有改动，所以如果用那个环境跑这个代码，会导致你这个问题。你可以重新安装这个repo的环境，是能够复现paper的结果的。

我当时开了一个新环境安装这个repo，然后能够复现结果，你可以再试一下。
