### ISSUE TITLE
nlu的 evaluation

### ISSUE THREAD

**Issue by JQIANG125** [thu-coai/CrossWOZ#17]
请问nlu的 evaluation是如何融合slot和intent的呢？

**Comment by zqwerty** [comment]
dialog act的标注是 [intent, domain, slot, value] 的形式，nlu模型最后需要给出这样形式的预测，然后计算f1。我们提供的BERTNLU模型，将value出现在utterance中的da识别当做slot tagging任务，其他da当做intent classification任务。可以参考[https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/nlu/jointBERT/crosswoz/postprocess.py](url)

**Comment by JQIANG125** [comment]
请问da是什么含义呢，还有数据中会有多意图的分类（一个句子多个意图）是怎么实现的呢？ “将value出现在utterance中的da识别当做slot tagging任务，其他da当做intent classification任务” 这句话是指 intent识别只是在句子不存在slot value的情况才做的吗？

**Comment by zqwerty** [comment]
> Based on pre-trained bert, BERTNLU use a linear layer for slot tagging and another linear layer for intent classification. Dialog acts are split into two groups, depending on whether the value is in the utterance. 
> 
> - For those dialog acts that the value appears in the utterance, they are translated to BIO tags. For example, `"Find me a cheap hotel"`, its dialog act is `{"Hotel-Inform":[["Price", "cheap"]]}`, and translated tag sequence is `["O", "O", "O", "B-Hotel-Inform+Price", "O"]`. An MLP takes bert word embeddings as input and classify the tag label. If you set `context=true` in config file, utterances of last three turn will be concatenated and provide context information with embedding of `[CLS]` for classification.  
> - For each of the other dialog acts, such as `(Hotel-Request, Address, ?)`, another MLP takes embeddings of `[CLS]` of current utterance as input and do the binary classification. If you set `context=true` in config file, utterances of last three turn will be concatenated and provide context information with embedding of `[CLS]` for classification.  

可以看看 https://github.com/thu-coai/CrossWOZ/tree/master/convlab2/nlu/jointBERT/crosswoz 这个目录下的preprocess.py
