### ISSUE TITLE
跑TRADE模型报错

### ISSUE THREAD

**Issue by aLowMagic** [thu-coai/CrossWOZ#19]
Traceback (most recent call last):
  File "convlab2/dst/trade/crosswoz/train.py", line 104, in <module>
    if(acc >= avg_best):
TypeError: '>=' not supported between instances of 'list' and 'float'
请问可不可以提供最新版本的代码呢

**Comment by nikitacs16** [comment]
Remove line 238 in convlab2/dst/trade/crosswoz/models/TRADE.py

**Comment by zhangzthu** [comment]
> Remove line 238 in convlab2/dst/trade/crosswoz/models/TRADE.py

That's right, we can fix this bug by removing this line. The code is updated.
