### ISSUE TITLE
请问可以提供区分S,M,M+T,CM,CM+T数据的代码吗

### ISSUE THREAD

**Issue by shanengcn** [thu-coai/CrossWOZ#21]
请问可以提供区分S,M,M+T,CM,CM+T数据的代码吗？想把数据分开单独测试，自己写的算出来和train的介绍不一样，谢谢

**Comment by zqwerty** [comment]
数据里面每个对话有type指示是哪一种

**Comment by shanengcn** [comment]
> 数据里面每个对话有type指示是哪一种

啊 好滴，看到了。多谢！
