### ISSUE TITLE
Check.

### ISSUE THREAD

**Issue by mianzhang** [thu-coai/CrossWOZ#23]
Hi,

I wonder whether the data in the repo is the same as those in repo https://github.com/thu-coai/ConvLab-2?
![image](https://user-images.githubusercontent.com/31158330/114396672-62eaf400-9bd0-11eb-9e15-8e78ca6424dd.png)

**Comment by zqwerty** [comment]
No. We fix some state labels in ConvLab-2 repo such as "酒店类型": "高档" => "酒店类型": "高档型". You can `diff [train|val|test].json` to see the difference.

**Comment by mianzhang** [comment]
Why you conduct these changes? I want to select a version of CrossWOZ to validate our model. Which version is better?

Best.

**Comment by zqwerty** [comment]
To unify the values ("高档" = "高档型") and correct some annotation errors. If you want to reproduce/compare the result in the paper, you can use the data in this repo. I think the data in ConvLab-2 repo is better, you can re-run the experiments with that one.

**Comment by mianzhang** [comment]
I get it.
