### ISSUE TITLE
DST中的Joint ACC问题

### ISSUE THREAD

**Issue by zhaokaihanyu** [thu-coai/CrossWOZ#24]
您好，请问DST任务，我用的https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_data.zip数据集中的test_dials.json 和 https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_model.zip提供的模型运行evaluate.py，joint acc最终只有24，比论文中的36.08低很多，然后将test_dials.json中的500个数据分成S，M，M+T，CM，CM+T之后，再每个evaluate，发现S得分80高于论文的71.67，其余都比论文低十几到二十分，（代码逻辑没有改，只把gating_dict = {"ptr":0, "none":1}改成了gating_dict = {"ptr": 0, "dontcare": 1, "none": 2}，因为不改这个的话和上面链接提供的模型冲突），所以我想确认一下我思路是不是有问题，或者测试数据用的和论文不一样，谢谢了。

**Comment by xiami2019** [comment]
> 您好，请问DST任务，我用的[https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_data.zip数据集中的test_dials.json](https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_data.zip%E6%95%B0%E6%8D%AE%E9%9B%86%E4%B8%AD%E7%9A%84test_dials.json) 和 [https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_model.zip提供的模型运行evaluate.py，joint](https://convlab.blob.core.windows.net/convlab-2/trade_crosswoz_model.zip%E6%8F%90%E4%BE%9B%E7%9A%84%E6%A8%A1%E5%9E%8B%E8%BF%90%E8%A1%8Cevaluate.py%EF%BC%8Cjoint) acc最终只有24，比论文中的36.08低很多，然后将test_dials.json中的500个数据分成S，M，M+T，CM，CM+T之后，再每个evaluate，发现S得分80高于论文的71.67，其余都比论文低十几到二十分，（代码逻辑没有改，只把gating_dict = {"ptr":0, "none":1}改成了gating_dict = {"ptr": 0, "dontcare": 1, "none": 2}，因为不改这个的话和上面链接提供的模型冲突），所以我想确认一下我思路是不是有问题，或者测试数据用的和论文不一样，谢谢了。

朋友你这个问题解决了吗

**Comment by xu-song** [comment]
+1
