### ISSUE TITLE
對於 sys_state, dialog_act 的疑問

### ISSUE THREAD

**Issue by peiwenhuang27** [thu-coai/CrossWOZ#26]
您好，近期在研究 CrossWOZ dataset 時對於 sys_state 等資訊有些疑問想請教：
1. 先前有在 issue 區看到其他發問提到 sys_state_init 是當前輪中初始做 db query 的結果，而 sys_state 是當前輪結束前的最後一次 db query，所以 sys_state_init 與 sys_state 是否的內容只差在一次 db query 前後補齊的資料呢？
2. 根據您的論文提到，db query 是在當前狀態中提取中 db 所有符合現今 constraint 的資訊，而確切 db query 的意義是什麼？舉例來說，若 user 要求系統 recommend 某某街上中價位的餐廳，系統就會根據 state 提供的條件（某某街、中價位）去 db query 出符合當前需求的候選嗎？
3. dialog_act、sys_state_init 及 sys_state 三者互相的關係，是否能請您舉例說明呢？例如 dialog_act 會在什麼時候被融入 sys_state，而他跟 db query 的時間點差異又是如何等。

非常感謝您！

**Comment by zqwerty** [comment]
1. 可能是多次dbquery。sys_state_init是第一次，sys_state是最后一次
2. 对，实际上我们就是用sys_state进行检索的
3. user inform的内容一般都会进入sys_state_init, 即系统第一次查询都是按照用户约束来的。如果找不到结果，可能就放松约束，多查几次，最后基于sys_state进行回复
