### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by hulumei123** [thu-coai/CrossWOZ#3]
请问提供的代码是：
端到端的实现方式？还是NLU、DST、NLG是相对独立的部分？

**Comment by zqwerty** [comment]
提供NLU等各个模块的代码，将各个模块组合起来可以进行端到端对话

**Comment by BoomBaYang** [comment]
请问，NLU等各个模块组合起来不应该是pipeline形式的吗，为什么说组合起来可以进行端到端对话？

**Comment by zqwerty** [comment]
这里是说使用上可以输入utterance输出utterance
