### ISSUE TITLE
关于论文中的SL policy准确率

### ISSUE THREAD

**Issue by HUSTHY** [thu-coai/CrossWOZ#30]
我采用该数据集以及你们提供的代码，跑出来的结果F1值为啥只有0.3125，(delex)F1值0.36
和论文的结果相差太大了，占时还没有想到是那里的问题，是数据集的问题还是代码的问题还是训练方式的问题？
模型训练代码中的注释给出的测试集F1值为0.77，我这边只有0.32；
难道有可能是评价指标计算问题？

**Comment by zqwerty** [comment]
你是否是按照README中安装本仓库然后再运行呢？这个仓库的代码应该都是能复现的，但是ConvLab-2官方仓库的代码有更新

**Comment by HUSTHY** [comment]
谢谢回复
我这边直接是把这个repo下的代码git clone到本地，然后按照README中数据链接下载数据，运行Policy中的MLE部分代码
初始化会自动下载你们提供的best model 这个在test集上单领域的F1值只有0.01，TP=1   提供的模型权重和当前数据集或者代码不适配
然后采用MLE下的代码直接训练一版，config.json也没有修改，训练完成后，训练集和测试集的F1值 差不太多 都是0.3左右
感觉是那里出现了问题
我再尝试使用ConvLab-2官方仓库的代码，训练一版看看

**Comment by HUSTHY** [comment]
我看论文中提到：
The state s consists of the last system dialogue acts, last user dialogue acts, system state of the current turn, the number of entities that satisfy the constraints in the current domain, and a terminal signal indicating whether the user goal is completed.
但是mle中的评测的时候
`        for i, turn in enumerate(sess['messages']):
            if turn['role'] == 'usr':
                dst.update(usr_da=turn['dialog_act'])#这一句并没有更新到用户的user_action
                if i + 2 == len(sess):
                    dst.state['terminated'] = True`
dst并没有update用户的act导致整个过程中模型的输入不对
最后才导致效果和论文中的不一样吧？！

**Comment by HUSTHY** [comment]
终于把你这个给弄对了你这个代码有点问题；需要dst更新用户的状态，这个才能和论文的思想一致
`dst.state['user_action'] = turn['dialog_act']`
训练的数据加载的时候以及测试的时候添加这个代码就可以了

**Comment by zqwerty** [comment]
我去确认一下，你是运行 `https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/policy/mle/crosswoz/train.py` 这个程序吗？

**Comment by zqwerty** [comment]
看了一下[修改记录](https://github.com/thu-coai/CrossWOZ/commit/1e40d74a46575ec7acb2ad8861f963a8785834f3)，你说的是对的，之前某次修改将DST中`dst.state['user_action'] = turn['dialog_act']`移到了agent 类中，会影响MLE训练时的数据处理。但是已经训好的模型似乎不会受到影响？你的结果都是运行了哪些程序呢？

**Comment by zqwerty** [comment]
> 终于把你这个给弄对了你这个代码有点问题；需要dst更新用户的act，这个才能和论文的思想一致 `dst.state['user_action'] = turn['dialog_act']` 训练的数据加载的时候以及测试的时候添加这个代码就可以了

我也修改后重新跑了一下，可以复现0.77的结果，多谢！已更新代码：https://github.com/thu-coai/CrossWOZ/commit/d8c800eefc8839ffb2cf86ff2c60a240f3ac4c09
