### ISSUE TITLE
关于端到端测试

### ISSUE THREAD

**Issue by unparalleled-ysj** [thu-coai/CrossWOZ#32]
你好，我想使用 BertNLU + RuleDST + RulePolicy + TemplateNLG 组一个 Agent 做端到端测试，但是在Policy部分的内容出现错误，应该如何正确使用Policy呢，代码如下：
`from convlab2.nlu.jointBERT.crosswoz import BERTNLU
from convlab2.dst.rule.crosswoz import RuleDST
from convlab2.policy.rule.crosswoz import Simulator
from convlab2.nlg.template.crosswoz import TemplateNLG
from convlab2.dialog_agent import PipelineAgent, BiSession

sys_nlu = BERTNLU()
    # simple rule DST
sys_dst = RuleDST()
# rule policy
sys_policy = Simulator()
# template NLG
sys_nlg = TemplateNLG(is_user=False)
# assemble
sys_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')

print(sys_agent.response('你好，北京大学附近有什么好吃的'))`

**Comment by zqwerty** [comment]
Simulator 不是系统侧的rule policy，而是user的policy。我们没有提供crosswoz的rule policy。可参考 https://github.com/thu-coai/CrossWOZ/issues/22#issuecomment-816595223。我们提供的是MLE policy

**Comment by unparalleled-ysj** [comment]
嗯我已经测试了，但是我发现这样的组合效果比较差，模型似乎没有联系上下文的能力，请问应该从什么方向去改进呢

**Comment by unparalleled-ysj** [comment]
好的，我还有个疑问，在ConvLab-2的论文中，为什么 BertNLU(MILU) + RuleDST + RulePolicy + TemplateNLG 组合的模型在各项指标上超出其他模型一大截，但是在CrossWOZ的组合上却表现的较差，是因为CrossWOZ的MLE Policy相比于MultiWOZ的Rule Policy不够鲁棒的原因吗

**Comment by zqwerty** [comment]
主要是policy的问题。在MultiWOZ上，RulePolicy比MLE要强，但是不能说谁更鲁棒。RulePolicy是人写的，费时费力。

**Comment by unparalleled-ysj** [comment]
好的，感谢你的耐心解答，顺便反馈个bug，测试TemplateNLG的时候出现问题
`python convlab2/nlg/template/crosswoz/nlg.py`
原因是预先设定的intent_order['sys']里面没有“ Request+地铁+出发地”  “ Inform+地铁+目的地”

**Comment by zqwerty** [comment]
多谢，已修正
