### ISSUE TITLE
关于TRADE模型在CrossWOZ数据集上的部署

### ISSUE THREAD

**Issue by yangpuhai** [thu-coai/CrossWOZ#33]
您好，
通过查看convlab2/dst/trade/crosswoz/utils/utils_multiWOZ_DST.py文件，貌似您还没有完成TRADE在CrossWOZ上的代码，我想请问一下，您在论文中所提及的TRADE在CrossWOZ上的结果是按照数据集中的哪个标注信息来实验的呢，sys_state或sys_state_init？还有，您的数据集中的DST任务的对话轮转否也是和MultiWOZ中[[sys,user],[sys,user],...]这种方式一致的呢？
谢谢

**Comment by zz-jacob** [comment]
1）参照readme的描述，代码是可以运行的，不知道您对utils_multiWOZ_DST.py有何疑问？
2）实验结果所使用的标注请参照config.py中的参数，为‘init'。
3）是一致的。

**Comment by yangpuhai** [comment]
谢谢
