### ISSUE TITLE
代码中存在请求生成nlg TemplateNLG类中的generate方法的入参的相关代码吗

### ISSUE THREAD

**Issue by zhangxiangchn** [thu-coai/CrossWOZ#34]
您好，我看了代码之后，想问一下，系统回复，TemplateNLG().generate() 方法的入参是如何生成的呢？这一块的代码是否存在？
举个例子：
假设用户asr为 "你好，麻烦帮我推荐一个门票免费,评分4分以上的景点。"， 
NLU的结果假设是：[["General","greet","none","none"],["Inform","景点","门票","免费"],["Inform", "景点", "评分","4分"],["Request","景点","名称",""]]，
在进行nlg之前，如何生成: [["Inform","景点","名称","养心殿"]] 结构的数据呢？
是直接调用dst.query方法进行查询和填充吗？希望能帮忙解读一下。

**Comment by zqwerty** [comment]
这是[dst](https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/dst/rule/crosswoz/dst.py)+[policy](https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/policy/policy.py)模块，可以参考[PipelineAgent](https://github.com/thu-coai/CrossWOZ/blob/master/convlab2/dialog_agent/agent.py#L39) 中模块的组合，或参考convlab-2的tutorial

**Comment by zhangxiangchn** [comment]
现有的rule_simulator是usr的policy？基于rule的sys policy有开源的计划吗？

**Comment by zqwerty** [comment]
对。我们没有实现crosswoz上的rule sys policy。
