### ISSUE TITLE
关于sys_state和sys_state_init的疑问

### ISSUE THREAD

**Issue by lexmen318** [thu-coai/CrossWOZ#6]
按照个人理解，这两项内容都是关于系统收集到的用户当前的状态信息（包括要求的参数和选择），而selectedResults从标注中来看可能是截止目前对话时，用户的选择或者系统最新推荐的选项。从大部分数据来看sys_state_init应该是体现用户的需求和最新选择，而sys_state应该是系统推荐（好像提供的不算）或提供的条件和选择，但仍存在如下疑问：
1）sys_state和sys_state_init两者的差异似乎还是不太清晰，有些时候下两者几乎完全相同（推荐给用户的用户没反对就算用户选择？）；而有些时候，_init中似乎又包含了更少的信息（表示虽然推荐，但是用户没有答应？）；有时候，系统推荐后，用户已经说“这周边还有其它餐馆吗?”，结果sys_state_init的selectedResults中还有系统推荐的选项。
2）对话轮次之间，状态存在跳跃，比如前一个对话中，还存在selectedResults“鲜鱼口老字号美食街”，后面的对话就消失了（按理状态应该是累积或者不断更新的吧？）
建议是否考虑将两个sys_state的信息合并，就是收集用户截止目前的所有要求和最新选择，系统推荐部分建议单独出来和MultiWOZ类似做成Recommend类型的Dialog_act（目前有部分Recommend，但也存在一些实际的Recommend用Inform了，比如：“为您推荐鲜鱼口老字号美食街，人均消费75元，有您想吃的美食街哦。”这里面就用了Inform）

**Comment by zqwerty** [comment]
> 从大部分数据来看sys_state_init应该是体现用户的需求和最新选择，而sys_state应该是系统推荐（好像提供的不算）或提供的条件和选择
是的。sys_state_init是系统当前轮里第一次查询数据库的表单。sys_state是系统最后一次查询的表单。是可能相同的。DST任务应该使用sys_state_init的数据。selectedResult是当前轮系统要使用的结果。状态确实会更新，可能原来的约束不再需要了，或者要求再推荐同一领域的（则原来的约束清空）。Recommend设计的是两个及以上的结果推荐。

**Comment by lexmen318** [comment]
好的，感谢你的即时回复！

**Comment by zqwerty** [comment]
@liebkne 抱歉没看到消息。是的，周边的都是这样。它们是福寿斋的周边餐馆，在数据库中属于福寿斋这个实体的“周边餐馆”属性
