### ISSUE TITLE
document about TRADE dst

### ISSUE THREAD

**Issue by wxm71** [thu-coai/CrossWOZ#7]
请问TRADE DST模型训练有相关文档吗

1.  看了下 `convlab2/dst/trade/crosswoz/README.md`, 里面好像还是TRADE的 `README`

2. 尝试运行了一下 `convlab2/dst/trade/crosswoz/create_data_cn.py`,  运行失败， 报 `data/crosswoz/test.json` 找不到

3. 手动将顶层目录data下的几个zip文件解压到 `data/crosswoz` 之后，开始能正常运行，但是会报 `FileNotFoundError: [Errno 2] No such file or directory: 'data/crosswoz/all_prediction_TRADE.json'`

谢谢

**Comment by zhangzthu** [comment]
To simplify model training, we refined the code.
Now, by directly running 'python train.py', the data will be downloaded automatically and the training will be started.

**Comment by wxm71** [comment]
> To simplify model training, we refined the code.
> Now, by directly running 'python train.py', the data will be downloaded automatically and the training will be started.

thanks for today's commits, I'll have a try
