### ISSUE TITLE
About the "is_terminated" function in rule simulator 

### ISSUE THREAD

**Issue by Leishuyu-bupt** [thu-coai/CrossWOZ#9]
Dear,
We find that there is no judgment whether the number of turns exceeds maximum turn. This is a bug？

**Comment by zqwerty** [comment]
The maximum turn is configured in end2end simulation, outside the simulator.

**Comment by Leishuyu-bupt** [comment]
> The maximum turn is configured in end2end simulation, outside the simulator.

OK, Thank you
